config/routes.rb
require 'sidekiq/web'

Neighborly::Application.routes.draw do
  get '/about', to: redirect('/learn')

  post :hooks, to: 'webhook/events#create'

  devise_for :users, path: '',
    path_names:  {
      sign_in:  :login,
      sign_out: :logout,
      sign_up:  :sign_up
    },
    controllers: {
      omniauth_callbacks: :omniauth_callbacks,
      sessions:           :sessions
    }


  devise_scope :user do
    post '/sign_up', to: 'devise/registrations#create', as: :sign_up
  end

  get '/thank_you' => "static#thank_you"

  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }

  # Mountable engines
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount Neighborly::Api::Engine => '/api/', as: :neighborly_api
  mount Neighborly::Dashboard::Engine => '/dashboard/', as: :neighborly_dashboard
  mount Neighborly::Balanced::Creditcard::Engine => '/balanced/creditcard/', as: :neighborly_balanced_creditcard
  mount Neighborly::Balanced::Bankaccount::Engine => '/balanced/bankaccount/', as: :neighborly_balanced_bankaccount
  mount Neighborly::Balanced::Engine => '/balanced/', as: :neighborly_balanced

  # Non production routes
  if Rails.env.development?
    resources :emails, only: [ :index, :show ]
  end

  # Channels
  constraints ChannelConstraint do
    namespace :channels, path: '' do
      get '/', to: 'profiles#show', as: :profile
      resources :channels_subscribers, only: [:index, :create, :destroy]

      namespace :admin do

        get '/', to: 'dashboard#index', as: :dashboard

        namespace :reports do
          resources :subscriber_reports, only: [ :index ]
        end

        resources :followers, only: [ :index ]

        resources :projects, only: [ :index, :update] do
          member do
            put 'launch'
            put 'reject'
            put 'push_to_draft'
            put 'approve'
          end
        end
      end

      resources :projects, only: [:new, :create]
      # NOTE We use index instead of create to subscribe comming back from auth via GET
      resource :channels_subscriber, only: [:show, :destroy], as: :subscriber
    end
  end

  mount Neighborly::Admin::Engine => '/admin/', as: :neighborly_admin

  # Root path should be after channel constraints
  root to: 'projects#index'

  # Static Pages
  get '/sitemap',               to: 'static#sitemap',             as: :sitemap
  get '/how-it-works',          to: 'static#how_it_works',        as: :how_it_works
  get "/faq",                   to: "static#faq",                 as: :faq
  get "/terms",                 to: "static#terms",               as: :terms
  get "/privacy",               to: "static#privacy",             as: :privacy
  get "/start",                 to: "projects#start",             as: :start
  get '/learn',                 to: 'static#learn',               as: :learn

  # Only accessible on development
  if Rails.env.development?
    get "/base",                to: "static#base",              as: :base
  end

  get "/discover/(:state)(/near/:near)(/category/:category)(/tags/:tags)(/search/:search)", to: "discover#index", as: :discover

  resources :tags, only: [:index]

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Temporary
  get '/projects/neuse-river-greenway-benches-draft', to: redirect('/projects/neuse-river-greenway-benches')

  resources :projects, except: [ :destroy ] do
    resources :faqs, controller: 'projects/faqs', only: [ :index, :create, :destroy ]
    resources :terms, controller: 'projects/terms', only: [ :index, :create, :destroy ]
    resources :updates, controller: 'projects/updates', only: [ :index, :create, :destroy ]

    collection do
      get 'video'
    end

    member do
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'comments'
      get 'reports'
      get 'budget'
      get 'success'
    end

    resources :rewards, except: :show do
      member do
        post 'sort'
      end
    end

    resources :contributions, controller: 'projects/contributions', except: :update do
      member do
        put 'credits_checkout'
      end
    end

    resources :matches, controller: 'projects/matches', except: %i(index update destroy)
  end

  scope :login, controller: :sessions do
    devise_scope :user do
      get   :set_new_user_email
      patch :confirm_new_user_email
    end
  end

  resources :users, path: 'neighbors' do
    resources :questions, controller: 'users/questions', only: [:new, :create]
    resources :projects, controller: 'users/projects', only: [ :index ]
    resources :contributions, controller: 'users/contributions', only: [:index] do
      member do
        get :request_refund
      end
    end

    resources :authorizations, controller: 'users/authorizations', only: [:destroy]
    resources :unsubscribes, only: [:create]
    member do
      get :settings
      get :credits
      get :payments
      get :edit
      put :update_email
      put :update_password
    end
  end

  get :contact, to: 'contacts#new'
  resources :contacts, only: [:create]

  resources :images, only: [:new, :create]

  namespace :markdown do
    resources :previewer, only: :create
  end

  # Redirect from old users url to the new
  get "/users/:id", to: redirect('neighbors/%{id}')

  # Temporary Routes
  get '/projects/57/video_embed', to: redirect('projects/ideagarden/video_embed')

  get "/set_email" => "users#set_email", as: :set_email_users
  get "/:id", to: redirect('projects/%{id}')
end

app/controllers/channels/admin/projects_controller.rb
module Channels::Admin
  class ProjectsController < BaseController
    has_scope :by_id, :pg_search, :user_name_contains, :order_by, :with_state
    has_scope :between_created_at, using: [ :start_at, :ends_at ], allow_blank: true

    before_filter do
      @total_projects =  channel.projects.size
    end

    [:approve, :launch, :reject, :push_to_draft].each do |name|
      define_method name do
        @project    = channel.projects.find_by_permalink!(params[:id])
        @project.send("#{name.to_s}!")
        redirect_to :back
      end
    end

    protected
    def begin_of_association_chain
      channel
    end

    def collection
      @projects = apply_scopes(channel.projects.page(params[:page]))
    end
  end
end

app/controllers/channels/projects_controller.rb
class Channels::ProjectsController < ProjectsController
  before_action :check_application_method, only: %w(new create)
  after_action :associate_with_channel, only: :create

  private

  def check_application_method
    if channel.has_external_application?
      raise ActionController::RoutingError.new('Channel has external application method.')
    end
  end

  def associate_with_channel
    resource.channels << channel
    resource.save
  end
end

app/controllers/projects/contributions_controller.rb
class Projects::ContributionsController < ApplicationController
  after_filter :verify_authorized, except: :index
  skip_before_filter :set_persistent_warning
  has_scope :available_to_count, type: :boolean
  has_scope :with_state
  has_scope :page, default: 1

  def index
    @project        = parent
    @contributions  = collection
    @active_matches = parent.matches.active
    if request.xhr? && params[:page] && params[:page].to_i > 1
      render collection
    end
  end

  def edit
    @project      = parent
    @contribution = resource
    authorize resource
  end

  def show
    @project      = parent
    @contribution = resource
    authorize resource
  end

  def new
    @project      = parent
    @contribution = ContributionForm.new(project: parent, user: current_user)
    authorize @contribution

    @rewards = [empty_reward] + @project.rewards.not_soon.remaining.order(:minimum_value)

    if params[:reward_id] && (selected_reward = @project.rewards.not_soon.find(params[:reward_id])) && !selected_reward.sold_out?
      @contribution.reward = selected_reward
      @contribution.value = "%0.0f" % selected_reward.minimum_value
    end
  end

  def create
    @project      = parent
    @contribution = ContributionForm.new(permitted_params[:contribution_form].
                                     merge(user: current_user,
                                           project: parent))

    @contribution.reward_id = nil if params[:contribution_form][:reward_id].to_i == 0
    authorize @contribution

    if @contribution.save
      session[:thank_you_contribution_id] = @contribution.id
      flash.delete(:notice)
      redirect_to edit_project_contribution_path(project_id: @project, id: @contribution.id)
    else
      flash.alert = t('controllers.projects.contributions.create.error')
      redirect_to new_project_contribution_path(@project)
    end
  end

  def credits_checkout
    @contribution = resource
    authorize resource
    if current_user.credits < @contribution.value
      flash.alert = t('controllers.projects.contributions.credits_checkout.no_credits')
      return redirect_to new_project_contribution_path(@contribution.project)
    end

    unless @contribution.confirmed?
      @contribution.update_attributes({ payment_method: 'Credits' })
      @contribution.confirm!
    end

    flash.notice = t('controllers.projects.contributions.credits_checkout.success')
    redirect_to project_contribution_path(parent, resource)
  end

  protected

  def permitted_params
    params.permit(policy(@contribution || ContributionForm).permitted_attributes)
  end

  def collection
    @contributions ||= apply_scopes(parent.contributions).available_to_display.where(matching_id: nil).order("confirmed_at DESC").per(10)
  end

  def empty_reward
    Reward.new(minimum_value: 0, description: t('controllers.projects.contributions.new.no_reward'))
  end

  def parent
    @parent ||= Project.find_by_permalink!(params[:project_id])
  end

  def resource
    @resource ||= parent.contributions.find(params[:id])
  end
end

app/controllers/projects/faqs_controller.rb
class Projects::FaqsController < ApplicationController
  after_filter :verify_authorized, except: :index
  inherit_resources
  defaults resource_class: ProjectFaq, collection_name: :project_faqs

  actions :index, :create, :destroy
  belongs_to :project, finder: :find_by_permalink!

  def index
    @project = parent
  end

  def create
    @project_faq = ProjectFaq.new(permitted_params[:project_faq].merge(project: parent))
    authorize @project_faq
    create! { project_faqs_path(parent) }
  end

  def destroy
    authorize resource
    destroy! { project_faqs_path(parent) }
  end

  private
  def permitted_params
    params.permit(policy(@project_faq || ProjectFaq).permitted_attributes)
  end

  def collection
    @faqs ||= end_of_association_chain.order('created_at desc')
  end
end

app/controllers/projects/matches_controller.rb
class Projects::MatchesController < ApplicationController
  before_filter :authenticate_user!
  after_filter :verify_authorized

  def new
    @project = parent
    @match   = parent.matches.build
    authorize @match
  end

  def create
    @project = parent
    @match   = Match.new(
      match_params.except(:starts_at, :finishes_at).
        merge(project: parent, user: current_user)
    )
    authorize @match

    @match.starts_at   = Date.strptime(
      match_params[:starts_at], '%m/%d/%y'
    ).in_time_zone
    @match.finishes_at = Date.strptime(
      match_params[:finishes_at], '%m/%d/%y'
    ).in_time_zone

    if @match.save
      redirect_to edit_project_match_path(parent, @match)
    else
      flash.alert = @match.errors.messages.values.flatten.to_sentence
      render 'new'
    end
  end

  def edit
    @project = parent
    @match   = resource
    authorize resource
  end

  def show
    @project = parent
    @match   = resource
    authorize resource
  end

  protected

  def match_params
    params.require(:match).permit(
      %i(
        starts_at
        finishes_at
        value_unit
        value
      )
    )
  end

  def parent
    @parent ||= Project.find_by_permalink!(params[:project_id])
  end

  def resource
    @resource ||= parent.matches.find(params[:id])
  end
end

app/controllers/projects/terms_controller.rb
class Projects::TermsController < ApplicationController
  after_filter :verify_authorized, except: :index
  inherit_resources
  defaults resource_class: ProjectDocument, collection_name: :project_documents

  actions :create, :destroy
  belongs_to :project, finder: :find_by_permalink!

  def index
    @project = parent
    @documents = parent.project_documents
  end

  def create
    @project_document = ProjectDocument.new(permitted_params[:project_document].
                                            merge(project: parent))
    authorize @project_document
    create! { project_terms_path(parent) }
  end

  def destroy
    authorize resource
    destroy! { project_terms_path(parent) }
  end

  private
  def permitted_params
    params.permit(policy(@project_document || ProjectDocument).permitted_attributes)
  end
end

app/controllers/projects/updates_controller.rb
class Projects::UpdatesController < ApplicationController
  after_filter :verify_authorized, except: :index
  inherit_resources
  actions :destroy
  belongs_to :project, finder: :find_by_permalink!

  def index
    @project = parent
    if request.xhr? && params[:page] && params[:page].to_i > 1
      render collection
    end
  end

  def create
    @update = Update.new(permitted_params[:update].
                         merge(project: parent, user: current_user))
    authorize @update
    @update.save
    render @update
  end

  def destroy
    authorize resource
    destroy! do
      if request.xhr?
        return render nothing: true
      else
        project_updates_path(parent)
      end
    end
  end

  private
  def permitted_params
    params.permit(policy(@update || Update).permitted_attributes)
  end

  def collection
    @updates ||= policy_scope(end_of_association_chain).order('created_at desc').page(params[:page]).per(3)
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  after_filter :verify_authorized, except: [:index, :video, :video_embed, :embed,
                                            :embed_panel, :comments, :budget,
                                            :reward_contact, :send_reward_email,
                                            :start]

  respond_to :html

  def new
    @project = Project.new(user: current_user)
    authorize @project
  end

  def index
    projects_vars = {
      #coming_soon: :soon,
      #ending_soon: :expiring,
      featured:    :featured,
      recommended: :recommends,
      successful:  :successful
    }

    projects_vars.each do |var_name, scope|
      instance_variable_set "@#{var_name}", ProjectsForHome.send(scope)
    end

    @successful = @successful.take(2) if browser.mobile?
    @channels = Channel.with_state('online').order('RANDOM()').limit(4)
    @press_assets = PressAsset.order('created_at DESC').limit(5)
  end

  def create
    @project = Project.new(permitted_params[:project].merge(user: current_user))
    authorize @project
    @project.save
    respond_with @project, location: success_project_path(@project)
  end

  def success
    authorize resource
  end

  def edit
    authorize resource
    respond_with resource
  end

  def update
    authorize resource
    respond_with Project.update(resource.id, permitted_params[:project]),
      location: edit_project_path(@project)
  end

  def show
    authorize resource
    set_facebook_url_admin(resource.user)
    render :about if request.xhr?
  end

  def comments
    @project = resource
  end

  def reports
    authorize resource
  end

  def budget
    @project = resource
  end

  %w(embed video_embed).each do |method_name|
    define_method method_name do
      @title = resource.name
      render layout: 'embed'
    end
  end

  def embed_panel
    @project = resource
    render layout: !request.xhr?
  end

  def start
    @projects = ProjectsForHome.successful[0..3]
    @channel  = channel.decorate if channel
  end

  private

  def permitted_params
    params.permit(policy(@project || Project).permitted_attributes)
  end

  def resource
    @project ||= Project.find_by_permalink!(params[:id])
  end

  def permitted_params
    params.permit(policy(@project || Project).permitted_attributes)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_box_classes(project, is_large, contribution, columns)
    classes = if contribution && !browser.mobile?
      'large large-12 medium-12'
    elsif is_large
      'large large-9 medium-8'
    else
      columns || 'large-3 medium-4'
    end
    classes << " #{project.category.to_s.parameterize}" if project.category
    classes << ' soon' if project.soon?

    classes << ' columns left'
  end

  def project_content_classes(project, is_large, contribution)
    if contribution && !browser.mobile?
      'large-3 medium-3 columns right'
    elsif is_large
      'large-4 medium-4 columns right'
    end
  end

  def remaining_days(project)
    [
      content_tag(:strong, project.remaining_days),
      project.time_to_go[:unit].capitalize,
      pluralize_without_number(project.time_to_go[:time],
                               t('words.remaining_singular'),
                               t('words.remaining_plural')
      )
    ].join(" ").html_safe
  end

  def display_status(project)
    content_tag :span do
      t("projects.show.display_status.#{project.campaign_type}.#{project.display_status}",
        goal: project.display_goal,
        date: (l(project.expires_at.to_date, format: :long) rescue nil))
    end
  end
end

app/views/channels/admin/projects/index.html.slim
.admin
  .row
    = render 'layouts/admin/channels_menu'
    section.content.large-12.columns
      h1
        = @title = t('channels.admin.management.title')
        ' :
        = @total_projects
        '
        = t('channels.admin.management.total')

      = simple_form_for '', url: channels_admin_projects_path, method: :get do |form|
        .row
          .large-3.columns
            = form.input 'between_created_at[start_at]', as: :string, label: t('channels.admin.filter.between_created_at'), input_html: { data: { mask: '99/99/9999' } }
          .large-3.columns
            br/
            = form.input 'between_created_at[ends_at]', as: :string, label: false, input_html: { class: 'custom', data: { mask: '99/99/9999' } }
          .large-3.columns
            = form.input :with_state, collection: Project.state_names, label: t('channels.admin.filter.with_state'), as: :select, selected: params[:with_state], include_blank: true
          .large-3.columns
            = form.input :pg_search, as: :string, label: t('channels.admin.filter.pg_search')
        .row
          .large-6.columns
            = form.input :user_name_contains, as: :string, label: t('channels.admin.filter.user_name_contains')
          .large-6.columns
            = form.input :order_by, label: t('channels.admin.filter.order_table'), as: :select, collection: [[t('.order_created_at'), 'created_at desc'], [t('.order_asc'), 'goal asc'], [t('.order_desc'), 'goal desc']], selected: params[:order_by]
        .row
          .large-12.columns.text-right
            = form.button :submit, t('channels.admin.filter.submit'), class: 'button medium negative'

      .row
        .large-6.columns.text-left
            = paginate @projects
        .large-6.columns.text-right
          = pluralize_without_number @projects.count, t('words.found_singular'), t('words.found_plural')
          | &nbsp;
          strong = @projects.count
          | &nbsp;
          = pluralize_without_number(@projects.count, t('words.project_singular'), t('words.project_plural')).downcase
      - if @projects.empty?
        = t('.no_contributions')
      - else
        table
          thead
            tr
              th= t('channels.admin.projects.index.name')
              th= t('channels.admin.projects.index.category')
              th= t('channels.admin.projects.index.user_id')
              th= t('channels.admin.projects.index.goal')
              th= t('channels.admin.projects.index.pledged')
              th= t('channels.admin.projects.index.total_contributions')
              th= t('channels.admin.projects.index.recommended')
              th= t('channels.admin.projects.index.online_date')
              th= t('channels.admin.projects.index.expires_at')
              th= t('channels.admin.projects.index.state')
              th
          tbody
            - @projects.includes(:category).each do |project|
              tr id=project.id
                td= link_to project.name, project_path(project)
                td= project.category
                td= project.user_id
                td= project.display_goal
                td= "#{project.display_pledged} (#{project.progress}%)"
                td= project.total_contributions
                td= project.recommended ? t('words._yes') : t('words._no')
                td= project.online_date.to_date if project.online_date
                td= project.display_expires_at
                td
                  - if project.online?
                    span.label.label-online= project.state
                  - elsif project.successful?
                    span.label.label-success= project.state
                  - elsif project.failed? or project.rejected?
                    span.label.label-important= project.state
                  - elsif project.waiting_funds?
                    span.label.label-warning= project.state
                  - else
                    span.label= project.state
                td.project-events-dropdown
                  = link_to 'javascript:void(0);', class: 'button tiny secondary', data: {dropdown: "dropdown-#{project.id}"} do
                    i.icon-et-down-dir
                  ul[id="dropdown-#{project.id}" data-dropdown-content class="f-dropdown"]
                    - if project.can_approve?
                      li
                        = link_to  approve_channels_admin_project_path(project), method: :put  do
                          i.icon-trash
                          = t('channels.admin.projects.index.approve')

                    - if project.can_launch?
                      li
                        = link_to launch_channels_admin_project_path(project), method: :put do
                          i.icon-ok
                          = t('channels.admin.projects.index.launch')

                    - if project.can_reject?
                      li
                        = link_to reject_channels_admin_project_path(project), method: :put  do
                          i.icon-ban-circle
                          = t('channels.admin.projects.index.reject')

                    - if project.can_push_to_draft?
                      li
                        = link_to  push_to_draft_channels_admin_project_path(project), method: :put  do
                          i.icon-trash
                          = t('channels.admin.projects.index.send_to_draft')

      = paginate @projects