config/routes.rb
require 'sidekiq/web'

Neighborly::Application.routes.draw do
  get '/about', to: redirect('/learn')

  post :hooks, to: 'webhook/events#create'

  devise_for :users, path: '',
    path_names:  {
      sign_in:  :login,
      sign_out: :logout,
      sign_up:  :sign_up
    },
    controllers: {
      omniauth_callbacks: :omniauth_callbacks,
      sessions:           :sessions
    }


  devise_scope :user do
    post '/sign_up', to: 'devise/registrations#create', as: :sign_up
  end

  get '/thank_you' => "static#thank_you"

  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }

  # Mountable engines
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount Neighborly::Api::Engine => '/api/', as: :neighborly_api
  mount Neighborly::Dashboard::Engine => '/dashboard/', as: :neighborly_dashboard
  mount Neighborly::Balanced::Creditcard::Engine => '/balanced/creditcard/', as: :neighborly_balanced_creditcard
  mount Neighborly::Balanced::Bankaccount::Engine => '/balanced/bankaccount/', as: :neighborly_balanced_bankaccount
  mount Neighborly::Balanced::Engine => '/balanced/', as: :neighborly_balanced

  # Non production routes
  if Rails.env.development?
    resources :emails, only: [ :index, :show ]
  end

  # Channels
  constraints ChannelConstraint do
    namespace :channels, path: '' do
      get '/', to: 'profiles#show', as: :profile
      resources :channels_subscribers, only: [:index, :create, :destroy]

      namespace :admin do

        get '/', to: 'dashboard#index', as: :dashboard

        namespace :reports do
          resources :subscriber_reports, only: [ :index ]
        end

        resources :followers, only: [ :index ]

        resources :projects, only: [ :index, :update] do
          member do
            put 'launch'
            put 'reject'
            put 'push_to_draft'
            put 'approve'
          end
        end
      end

      resources :projects, only: [:new, :create]
      # NOTE We use index instead of create to subscribe comming back from auth via GET
      resource :channels_subscriber, only: [:show, :destroy], as: :subscriber
    end
  end

  mount Neighborly::Admin::Engine => '/admin/', as: :neighborly_admin

  # Root path should be after channel constraints
  root to: 'projects#index'

  # Static Pages
  get '/sitemap',               to: 'static#sitemap',             as: :sitemap
  get '/how-it-works',          to: 'static#how_it_works',        as: :how_it_works
  get "/faq",                   to: "static#faq",                 as: :faq
  get "/terms",                 to: "static#terms",               as: :terms
  get "/privacy",               to: "static#privacy",             as: :privacy
  get "/start",                 to: "projects#start",             as: :start
  get '/learn',                 to: 'static#learn',               as: :learn

  # Only accessible on development
  if Rails.env.development?
    get "/base",                to: "static#base",              as: :base
  end

  get "/discover/(:state)(/near/:near)(/category/:category)(/tags/:tags)(/search/:search)", to: "discover#index", as: :discover

  resources :tags, only: [:index]

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Temporary
  get '/projects/neuse-river-greenway-benches-draft', to: redirect('/projects/neuse-river-greenway-benches')

  resources :projects, except: [ :destroy ] do
    resources :faqs, controller: 'projects/faqs', only: [ :index, :create, :destroy ]
    resources :terms, controller: 'projects/terms', only: [ :index, :create, :destroy ]
    resources :updates, controller: 'projects/updates', only: [ :index, :create, :destroy ]

    collection do
      get 'video'
    end

    member do
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'comments'
      get 'reports'
      get 'budget'
      get 'success'
    end

    resources :rewards, except: :show do
      member do
        post 'sort'
      end
    end

    resources :contributions, controller: 'projects/contributions', except: :update do
      member do
        put 'credits_checkout'
      end
    end

    resources :matches, controller: 'projects/matches', except: %i(index update destroy)
  end

  scope :login, controller: :sessions do
    devise_scope :user do
      get   :set_new_user_email
      patch :confirm_new_user_email
    end
  end

  resources :users, path: 'neighbors' do
    resources :questions, controller: 'users/questions', only: [:new, :create]
    resources :projects, controller: 'users/projects', only: [ :index ]
    resources :contributions, controller: 'users/contributions', only: [:index] do
      member do
        get :request_refund
      end
    end

    resources :authorizations, controller: 'users/authorizations', only: [:destroy]
    resources :unsubscribes, only: [:create]
    member do
      get :settings
      get :credits
      get :payments
      get :edit
      put :update_email
      put :update_password
    end
  end

  get :contact, to: 'contacts#new'
  resources :contacts, only: [:create]

  resources :images, only: [:new, :create]

  namespace :markdown do
    resources :previewer, only: :create
  end

  # Redirect from old users url to the new
  get "/users/:id", to: redirect('neighbors/%{id}')

  # Temporary Routes
  get '/projects/57/video_embed', to: redirect('projects/ideagarden/video_embed')

  get "/set_email" => "users#set_email", as: :set_email_users
  get "/:id", to: redirect('projects/%{id}')
end

app/controllers/channels/admin/projects_controller.rb
module Channels::Admin
  class ProjectsController < BaseController
    has_scope :by_id, :pg_search, :user_name_contains, :order_by, :with_state
    has_scope :between_created_at, using: [ :start_at, :ends_at ], allow_blank: true

    before_filter do
      @total_projects =  channel.projects.size
    end

    [:approve, :launch, :reject, :push_to_draft].each do |name|
      define_method name do
        @project    = channel.projects.find_by_permalink!(params[:id])
        @project.send("#{name.to_s}!")
        redirect_to :back
      end
    end

    protected
    def begin_of_association_chain
      channel
    end

    def collection
      @projects = apply_scopes(channel.projects.page(params[:page]))
    end
  end
end

app/controllers/channels/projects_controller.rb
class Channels::ProjectsController < ProjectsController
  before_action :check_application_method, only: %w(new create)
  after_action :associate_with_channel, only: :create

  private

  def check_application_method
    if channel.has_external_application?
      raise ActionController::RoutingError.new('Channel has external application method.')
    end
  end

  def associate_with_channel
    resource.channels << channel
    resource.save
  end
end

app/controllers/projects/contributions_controller.rb
class Projects::ContributionsController < ApplicationController
  after_filter :verify_authorized, except: :index
  skip_before_filter :set_persistent_warning
  has_scope :available_to_count, type: :boolean
  has_scope :with_state
  has_scope :page, default: 1

  def index
    @project        = parent
    @contributions  = collection
    @active_matches = parent.matches.active
    if request.xhr? && params[:page] && params[:page].to_i > 1
      render collection
    end
  end

  def edit
    @project      = parent
    @contribution = resource
    authorize resource
  end

  def show
    @project      = parent
    @contribution = resource
    authorize resource
  end

  def new
    @project      = parent
    @contribution = ContributionForm.new(project: parent, user: current_user)
    authorize @contribution

    @rewards = [empty_reward] + @project.rewards.not_soon.remaining.order(:minimum_value)

    if params[:reward_id] && (selected_reward = @project.rewards.not_soon.find(params[:reward_id])) && !selected_reward.sold_out?
      @contribution.reward = selected_reward
      @contribution.value = "%0.0f" % selected_reward.minimum_value
    end
  end

  def create
    @project      = parent
    @contribution = ContributionForm.new(permitted_params[:contribution_form].
                                     merge(user: current_user,
                                           project: parent))

    @contribution.reward_id = nil if params[:contribution_form][:reward_id].to_i == 0
    authorize @contribution

    if @contribution.save
      session[:thank_you_contribution_id] = @contribution.id
      flash.delete(:notice)
      redirect_to edit_project_contribution_path(project_id: @project, id: @contribution.id)
    else
      flash.alert = t('controllers.projects.contributions.create.error')
      redirect_to new_project_contribution_path(@project)
    end
  end

  def credits_checkout
    @contribution = resource
    authorize resource
    if current_user.credits < @contribution.value
      flash.alert = t('controllers.projects.contributions.credits_checkout.no_credits')
      return redirect_to new_project_contribution_path(@contribution.project)
    end

    unless @contribution.confirmed?
      @contribution.update_attributes({ payment_method: 'Credits' })
      @contribution.confirm!
    end

    flash.notice = t('controllers.projects.contributions.credits_checkout.success')
    redirect_to project_contribution_path(parent, resource)
  end

  protected

  def permitted_params
    params.permit(policy(@contribution || ContributionForm).permitted_attributes)
  end

  def collection
    @contributions ||= apply_scopes(parent.contributions).available_to_display.where(matching_id: nil).order("confirmed_at DESC").per(10)
  end

  def empty_reward
    Reward.new(minimum_value: 0, description: t('controllers.projects.contributions.new.no_reward'))
  end

  def parent
    @parent ||= Project.find_by_permalink!(params[:project_id])
  end

  def resource
    @resource ||= parent.contributions.find(params[:id])
  end
end

app/controllers/projects/faqs_controller.rb
class Projects::FaqsController < ApplicationController
  after_filter :verify_authorized, except: :index
  inherit_resources
  defaults resource_class: ProjectFaq, collection_name: :project_faqs

  actions :index, :create, :destroy
  belongs_to :project, finder: :find_by_permalink!

  def index
    @project = parent
  end

  def create
    @project_faq = ProjectFaq.new(permitted_params[:project_faq].merge(project: parent))
    authorize @project_faq
    create! { project_faqs_path(parent) }
  end

  def destroy
    authorize resource
    destroy! { project_faqs_path(parent) }
  end

  private
  def permitted_params
    params.permit(policy(@project_faq || ProjectFaq).permitted_attributes)
  end

  def collection
    @faqs ||= end_of_association_chain.order('created_at desc')
  end
end

app/controllers/projects/matches_controller.rb
class Projects::MatchesController < ApplicationController
  before_filter :authenticate_user!
  after_filter :verify_authorized

  def new
    @project = parent
    @match   = parent.matches.build
    authorize @match
  end

  def create
    @project = parent
    @match   = Match.new(
      match_params.except(:starts_at, :finishes_at).
        merge(project: parent, user: current_user)
    )
    authorize @match

    @match.starts_at   = Date.strptime(
      match_params[:starts_at], '%m/%d/%y'
    ).in_time_zone
    @match.finishes_at = Date.strptime(
      match_params[:finishes_at], '%m/%d/%y'
    ).in_time_zone

    if @match.save
      redirect_to edit_project_match_path(parent, @match)
    else
      flash.alert = @match.errors.messages.values.flatten.to_sentence
      render 'new'
    end
  end

  def edit
    @project = parent
    @match   = resource
    authorize resource
  end

  def show
    @project = parent
    @match   = resource
    authorize resource
  end

  protected

  def match_params
    params.require(:match).permit(
      %i(
        starts_at
        finishes_at
        value_unit
        value
      )
    )
  end

  def parent
    @parent ||= Project.find_by_permalink!(params[:project_id])
  end

  def resource
    @resource ||= parent.matches.find(params[:id])
  end
end

app/controllers/projects/terms_controller.rb
class Projects::TermsController < ApplicationController
  after_filter :verify_authorized, except: :index
  inherit_resources
  defaults resource_class: ProjectDocument, collection_name: :project_documents

  actions :create, :destroy
  belongs_to :project, finder: :find_by_permalink!

  def index
    @project = parent
    @documents = parent.project_documents
  end

  def create
    @project_document = ProjectDocument.new(permitted_params[:project_document].
                                            merge(project: parent))
    authorize @project_document
    create! { project_terms_path(parent) }
  end

  def destroy
    authorize resource
    destroy! { project_terms_path(parent) }
  end

  private
  def permitted_params
    params.permit(policy(@project_document || ProjectDocument).permitted_attributes)
  end
end

app/controllers/projects/updates_controller.rb
class Projects::UpdatesController < ApplicationController
  after_filter :verify_authorized, except: :index
  inherit_resources
  actions :destroy
  belongs_to :project, finder: :find_by_permalink!

  def index
    @project = parent
    if request.xhr? && params[:page] && params[:page].to_i > 1
      render collection
    end
  end

  def create
    @update = Update.new(permitted_params[:update].
                         merge(project: parent, user: current_user))
    authorize @update
    @update.save
    render @update
  end

  def destroy
    authorize resource
    destroy! do
      if request.xhr?
        return render nothing: true
      else
        project_updates_path(parent)
      end
    end
  end

  private
  def permitted_params
    params.permit(policy(@update || Update).permitted_attributes)
  end

  def collection
    @updates ||= policy_scope(end_of_association_chain).order('created_at desc').page(params[:page]).per(3)
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  after_filter :verify_authorized, except: [:index, :video, :video_embed, :embed,
                                            :embed_panel, :comments, :budget,
                                            :reward_contact, :send_reward_email,
                                            :start]

  respond_to :html

  def new
    @project = Project.new(user: current_user)
    authorize @project
  end

  def index
    projects_vars = {
      #coming_soon: :soon,
      #ending_soon: :expiring,
      featured:    :featured,
      recommended: :recommends,
      successful:  :successful
    }

    projects_vars.each do |var_name, scope|
      instance_variable_set "@#{var_name}", ProjectsForHome.send(scope)
    end

    @successful = @successful.take(2) if browser.mobile?
    @channels = Channel.with_state('online').order('RANDOM()').limit(4)
    @press_assets = PressAsset.order('created_at DESC').limit(5)
  end

  def create
    @project = Project.new(permitted_params[:project].merge(user: current_user))
    authorize @project
    @project.save
    respond_with @project, location: success_project_path(@project)
  end

  def success
    authorize resource
  end

  def edit
    authorize resource
    respond_with resource
  end

  def update
    authorize resource
    respond_with Project.update(resource.id, permitted_params[:project]),
      location: edit_project_path(@project)
  end

  def show
    authorize resource
    set_facebook_url_admin(resource.user)
    render :about if request.xhr?
  end

  def comments
    @project = resource
  end

  def reports
    authorize resource
  end

  def budget
    @project = resource
  end

  %w(embed video_embed).each do |method_name|
    define_method method_name do
      @title = resource.name
      render layout: 'embed'
    end
  end

  def embed_panel
    @project = resource
    render layout: !request.xhr?
  end

  def start
    @projects = ProjectsForHome.successful[0..3]
    @channel  = channel.decorate if channel
  end

  private

  def permitted_params
    params.permit(policy(@project || Project).permitted_attributes)
  end

  def resource
    @project ||= Project.find_by_permalink!(params[:id])
  end

  def permitted_params
    params.permit(policy(@project || Project).permitted_attributes)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_box_classes(project, is_large, contribution, columns)
    classes = if contribution && !browser.mobile?
      'large large-12 medium-12'
    elsif is_large
      'large large-9 medium-8'
    else
      columns || 'large-3 medium-4'
    end
    classes << " #{project.category.to_s.parameterize}" if project.category
    classes << ' soon' if project.soon?

    classes << ' columns left'
  end

  def project_content_classes(project, is_large, contribution)
    if contribution && !browser.mobile?
      'large-3 medium-3 columns right'
    elsif is_large
      'large-4 medium-4 columns right'
    end
  end

  def remaining_days(project)
    [
      content_tag(:strong, project.remaining_days),
      project.time_to_go[:unit].capitalize,
      pluralize_without_number(project.time_to_go[:time],
                               t('words.remaining_singular'),
                               t('words.remaining_plural')
      )
    ].join(" ").html_safe
  end

  def display_status(project)
    content_tag :span do
      t("projects.show.display_status.#{project.campaign_type}.#{project.display_status}",
        goal: project.display_goal,
        date: (l(project.expires_at.to_date, format: :long) rescue nil))
    end
  end
end

app/views/projects/_author.html.slim
section.author
  .row
    - if @project.user.organization?
      .large-5.columns
        = link_to @project.user.display_image_html(width: 300, height: 150, class: 'large'), @project.user
    - else
      .large-3.columns
        = link_to @project.user.display_image_html(width: 150, height: 150, class: 'large'), @project.user

    .columns[class="large-#{ @project.user.organization? ? 7 : 9}"]
      h4 = t('.author.about', name: link_to(@project.user.display_name, @project.user)).html_safe
      p = @project.user.bio

      .social
        ul
          - if @project.user.facebook_url.present?
            li = link_to @project.user.facebook_url, target: :blank, class: 'facebook' do
             i.icon-et-facebook-circled
          - if @project.user.twitter_url.present?
            li = link_to @project.user.twitter_url, target: :blank, class: 'twitter' do
             i.icon-et-twitter-circled
          - if @project.user.other_url.present?
            li = link_to @project.user.other_url, target: :blank, class: 'other' do
             i.icon-et-globe

      - if current_user.present?
        = link_to t('.ask_a_question'), new_user_question_path(@project.user, project_id: @project.id), data: { 'reveal-id' => 'ask-a-question', 'reveal-ajax' => true }, class: 'button ask-a-question-button'
      - else
        = link_to t('.ask_a_question'), new_user_session_path(redirect_to: project_path(@project, anchor: 'open-new-user-question-modal')), class: 'button ask-a-question-button'
      - content_for :modals do
        #ask-a-question.reveal-modal.small.fixed

app/views/projects/_header.html.slim
= hero_header_tag @project, class: ('no-image' if browser.mobile?) do
  .row
    .large-12.columns
      .name
        h3 = @project.name
    .large-8.medium-8.columns.no-padding-for-small
      .flex-video.widescreen.vimeo
        iframe src="#{@project.display_video_embed_url}" width="636 " height="358" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen
      .row.hide-for-medium-down
        .large-6.small-8.columns.share-small
          = render 'projects/share'
        .large-6.small-4.columns.time-remaining
          i.icon-et-clock
          = remaining_days(@project)

    .large-4.medium-4.columns
      .subtitle
        h5= t(".subtitle.#{@project.campaign_type}", category_name: link_to(@project.category, discover_path(category: @project.category.to_s.downcase)), city: @project.display_address_formated, author: link_to(@project.user.display_name, user_path(@project.user))).html_safe
      hr
      .headline
        p = @project.headline
      .status
        = @project.progress_bar
        .pledged.hide-for-medium
          = @project.display_pledged
          small = t('.so_far').html_safe
          = @project.display_goal
        .pledged.show-for-medium
          = @project.display_pledged
          small = t('.reached_goal_small_separator_html')
          = @project.display_goal
      - if @project.online? && !@project.expired?
        .show-for-small
          .contribute-top
            = link_to t('.contribute'), new_project_contribution_url(@project), class: "button with-icon contribute"

app/views/projects/_matches.html.slim
- if @project.matches.active.any?
  .row.matches
    .large-12.columns.match-summary
      h3 = t('.match_summary',
            base_value: number_to_currency(1, precision: 0),
            worth_value: number_to_currency(@project.matches.active.sum(:value_unit) + 1, precision: 0),
            date: l(@project.matches.active.minimum(:finishes_at), format: :long))

    - for match in @project.matches.active.order(:finishes_at)
      .large-12.columns.match-description
        span
          = t('.match_description',
              user_name: link_to(match.user.display_name, match.user),
              value_unit: number_to_currency(match.value_unit, precision: 0),
              base_value: number_to_currency(1, precision: 0),
              limit: number_to_currency(match.value, precision: 0)).html_safe

app/views/projects/_project.html.slim
- large = defined?(large) && large
- if !defined?(:contribution)
  - contribution = nil

= cache [:project_box, project, project.progress, project.pledged, large, contribution, defined?(:columns), browser.mobile?, browser.ie8?, project.remaining_days] do

  .project-box[itemscope itemtype="http://schema.org/CreativeWork" class=project_box_classes(project, large, contribution, try(:columns))]
    meta[ itemprop="dateCreated" content=project.created_at.to_date ]
    - if project.soon?
      - project_link = 'javascript:void(0)'
    - else
      - project_link = project_path(project)

    = link_to project_link, target: (defined?(embed_link) ? :blank : '') do
      - if project.expired?
        .status-image
          - if project.successful? && project.reached_goal?
            = image_tag "successful.#{I18n.locale}.png"
          - elsif project.successful? && !project.reached_goal?
            = image_tag "successful_flex.#{I18n.locale}.png"
          - elsif project.failed?
            = image_tag "not_successful.#{I18n.locale}.png"
      - elsif project.soon?
        .status-image
          = image_tag "coming_soon.#{I18n.locale}.png"

      .row
        .cover.small-12.columns
          = image_tag project.display_image(large || contribution && !browser.mobile? ? 'project_thumb_large' : 'project_thumb'), itemprop: 'image'

      - if contribution && !browser.mobile?
        .back-informations.large-3.medium-3.columns.right
          h5
            - contribution.confirmed_at.present?
              i.icon-et-calendar
              = l contribution.confirmed_at.to_date, format: :long

          - if contribution.display_value
            h5
              i.icon-et-heart
              = contribution.display_value
          - if contribution.reward
            .reward
              h5
                i.icon-et-trophy
                = t('rewards.index.reward_title', minimum: contribution.reward.display_minimum)
              - description = contribution.reward.description.gsub(/"/,'&quot;')
              p[title=description] = truncate(contribution.reward.description, length: 160)

          .share.row
            .large-6.columns
              = link_to t('.share.facebook'), "http://www.facebook.com/sharer.php?s=100&p[title]=#{project.name}&p[summary]=#{project.headline}&p[url]=#{project_url(project)}&p[images[0]=#{project.display_image('project_thumb_facebook')}", class: 'button with-icon facebook', target: :blank
            .large-6.columns
              = link_to t('.share.twitter'), "https://twitter.com/intent/tweet?text=#{URI::encode(t('.share.twitter-text', name: project.name, hash_tag: project.hash_tag))}", class: 'button with-icon twitter', target: :blank

      .content[class=project_content_classes(project, large, contribution)]
        - if large || contribution && !browser.mobile?
          h4.name = project.name

        .category
          i[title=project.category.to_s]
          span = project.category.to_s

        - unless large || contribution && !browser.mobile?
          h4.name = project.name

        .location
          i.icon-et-location
          | &nbsp;
          = project.location

        - if (large || !browser.ie8? || contribution && !browser.mobile?)
          .description.hide-for-small[itemprop='description']
            span = truncate(project.headline, length: 140, separator: ' ')
            a

        .status
          .row.collapse
            .pledged.large-6.columns = "#{project.display_pledged} (#{project.progress}%)"
            .time.project.large-6.columns
              i.icon-et-clock
              - if project.soon?
                = t('.soon')
              - elsif project.expired?
                = t('.completed')
              - else
                = "#{project.time_to_go[:time]} #{project.time_to_go[:unit]} #{project.remaining_text}"
          = project.progress_bar

app/views/projects/_status_bar.html.slim
section.status-bar.fixed
  .row
    .large-12.columns.status
      .row
        .large-3.columns.share-small.hide-for-medium-down
          = render 'projects/share', embed: false
        .large-2.columns.pledged.hide-for-medium-down
          p = "#{@project.display_pledged} (#{@project.progress}%)"
        .large-2.columns.contributions.hide-for-medium-down
          p
            i.icon-et-user
            = t('.total_contributions', value: @project.total_contributions)
        .large-2.columns.time-remaining.hide-for-medium-down
          p
            i.icon-et-clock
            = remaining_days(@project)

        - if @project.online? && !@project.expired?
          .large-3.columns.contribute
            = link_to t('.contribute'), new_project_contribution_url(@project), class: 'button small'
        - else
          .large-3.columns.status-description
            = display_status(@project)

app/views/projects/_tabs.html.slim
nav.tabs[data-target-container=".project-page section.content"]
  ul
    li = tab_link_to t('.about'), project_path(@project)

    - if policy(@project).update? || @project.updates.size > 0
      li = tab_link_to project_updates_path(@project) do
        = t('.updates')
        span.count=" #{@project.updates.size}"

    - if @project.total_contributions_without_matches > 0
      li = tab_link_to project_contributions_path(@project) do
        = t('.contributions')
        span.count=" #{@project.total_contributions_without_matches}"

    li = tab_link_to comments_project_path(@project) do
      = t('.comments')
      span.commentsCount.count style="display: none;"
        span#countNumber

    li = tab_link_to t('.faqs'), project_faqs_path(@project) if @project.project_faqs.any? || policy(@project).update?
    li = tab_link_to t('.budget'), budget_project_path(@project) if @project.budget.present?
    li = tab_link_to t('.terms'), project_terms_path(@project) if @project.terms.present? || @project.project_documents.any? || policy(@project).update?
    - if policy(@project).update?
      li = tab_link_to t('.reports'), reports_project_path(@project), 'private'

app/views/projects/reports.html.slim
- content_for :page_content do
  - selected_r = @project.selected_rewards
  .panel
    = t('.link_reports')
    = link_to t('.all_contributions'), reports_contribution_reports_for_project_owners_path(project_id: @project.id, format: :csv)
  .panel
    = t('.link_reports')
    = link_to t('.all_contributions_without_reward'), reports_contribution_reports_for_project_owners_path(project_id: @project.id, reward_id: 0, format: :csv)
  - if selected_r.length > 0
      - selected_r.each do |reward|
        .panel
          p
            = t('.link_reward')
            = link_to reward.display_minimum, reports_contribution_reports_for_project_owners_path(project_id: @project.id, reward_id: reward.id, format: :csv)
- if request.xhr?
  = yield :page_content
- else
  = render template: 'projects/show'

app/views/projects/show.html.slim
- content_for :title, @project.name
= render partial: 'layouts/disqus_count'
= render 'projects/meta_tags'

.project-page
  = render 'projects/header'
  = render 'projects/status_bar'

  .row.page-main-content
    section.large-9.medium-8.columns.main
      = render 'projects/draft_warning' if @project.draft?
      = render 'projects/rejected_warning' if @project.rejected?
      = render 'projects/matches'
      = link_to t('.edit'), edit_project_path(@project), class: 'button edit show-for-small' if policy(@project).update?
      = render 'projects/tabs'

      section.content
        - if content_for? :page_content
          = yield :page_content
        - else
          = render template: 'projects/about', locals: { partial: true }

      = render 'projects/author' unless browser.mobile?

    aside.large-3.medium-4.columns.sidebar
      .call-to-action
        - if @project.online? && !@project.expired?
          = render 'projects/noscript'

          = link_to t('.contribute'), new_project_contribution_url(@project), class: "button with-icon contribute hide-for-small"
          - if current_user && (current_user.organization? || current_user.channel? || current_user.admin?)
            = link_to t('.create_match'), new_project_match_url(@project), class: "button with-icon create-match hide-for-small"
        - else
          .alert-box.secondary.status-description
            = display_status(@project)

        = link_to t('.edit'), edit_project_path(@project), class: 'button edit hide-for-small' if policy(@project).update?

        = render 'projects/matches_aside' unless browser.mobile?

      - if @project.last_channel
        section.channel
          = link_to root_url(subdomain: @project.last_channel.permalink, protocol: :http) do
            .row
              .large-12.columns.large-centered
                h5 = t('.in_partnership_with')
                = image_tag @project.last_channel.image.large.url

      - if @project.total_contributions_without_matches > 0
        section.custom.neighbors-behind-this.hide-for-medium-down
          .title = t('.neighbors_behind_this')
          .list
            - for contribution in @project.contributions.available_to_display.includes(:user).where(matching_id: nil).order("RANDOM()").limit(15)
              - if contribution.anonymous
                = link_to image_tag('anonymous-user.png'), '#', title: t('.anonymous_contribution'), class: 'has-tip', data: { tooltip: '' }
              - else
                = link_to image_tag(contribution.user.display_image), user_path(contribution.user), title: contribution.user.display_name, class: 'has-tip', data: { tooltip: '' }
          .more
            = link_to pluralize(@project.total_contributions, t('words.neighbor_singular'), t('words.neighbor_plural')), project_contributions_path(@project)

      section.rewards[data-rewards-path=project_rewards_path(@project) data-can-update="#{policy(@project).update?}"]

      = render 'projects/author' if browser.mobile?